dap-root = "Assets/Standard Assets/_Dap"
dap-editor-root = "Assets/Standard Assets/Editor/_DapEditor"

ext-root = "Assets/Standard Assets/_Ext"
ext-editor-root = "Assets/Standard Assets/Editor/_ExtEditor"

mod-root = "Assets/Standard Assets/_Mod"
mod-editor-root = "Assets/Standard Assets/Editor/_ModEditor"

assets-root = "Assets"

[dap-core]
[[dap-core.folders]]
from = "Scripts/DapCore"
to = "${dap-root}/_DapCore"

