dap-root = "Assets/Standard Assets/_Dap"
dap-editor-root = "Assets/Standard Assets/Editor/_Dap"
dap-version = "0.5.0"

[dap-core]
[[dap-core.files]]
from = "Releases/${dap-version}"
to = "${dap-root}"
include = "DapCore-*.*"

[dap-core-src]
[[dap-core-src.folders]]
from = "Scripts/DapCore"
to = "${dap-root}/_DapCore"

